# Generated by Django 3.1.3 on 2020-11-22 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_category', models.CharField(choices=[('Influencer', 'Influencer'), ('Makeup Artist', 'Makeup Artist'), ('Photographer', 'Photographer')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name: ', max_length=50)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact Number: ', max_length=128, region=None, unique=True)),
                ('dob', models.DateField(help_text='Date Of Birth: ')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], help_text='Gender: ', max_length=1)),
                ('location', models.TextField(help_text='Location: ', max_length=500)),
                ('category', models.CharField(choices=[('Social Media Star', 'Social Media Star'), ('Mom/Dad Influencer', 'Mom/Dad Influencer'), ('Free Lancer', 'Free Lancer'), ('Campus Ambassador', 'Campus Ambassador'), ('Working Professional', 'Working Professional')], help_text='Pick your Category: ', max_length=40)),
                ('instagram_username', models.CharField(default='', max_length=256)),
                ('instagram_followers', models.IntegerField(default=50)),
                ('twitter_username', models.CharField(default='', max_length=256)),
                ('twitter_followers', models.IntegerField(default=50)),
                ('youtube_username', models.CharField(default='', max_length=256)),
                ('youtube_followers', models.IntegerField(default=50)),
                ('linkedin_username', models.CharField(default='', max_length=256)),
                ('linkddin_followers', models.IntegerField(default=50)),
                ('snapchat_username', models.CharField(default='', max_length=256)),
                ('snapchat_followers', models.IntegerField(default=50)),
                ('pinterest_username', models.CharField(default='', max_length=256)),
                ('pinterest_followers', models.IntegerField(default=50)),
                ('tumbler_username', models.CharField(default='', max_length=256)),
                ('tumbler_followers', models.IntegerField(default=50)),
                ('github_username', models.CharField(default='', max_length=256)),
                ('github_followers', models.IntegerField(default=50)),
                ('dribble_username', models.CharField(default='', max_length=256)),
                ('dribble_followers', models.IntegerField(default=50)),
                ('fashion', models.BooleanField(default=True)),
                ('beautyandmakeup', models.BooleanField(default=False)),
                ('automobile', models.BooleanField(default=False)),
                ('arts', models.BooleanField(default=False)),
                ('movieandtv', models.BooleanField(default=False)),
                ('foodandbeverage', models.BooleanField(default=False)),
                ('musicanddance', models.BooleanField(default=False)),
                ('lifestyle', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('businessandstartup', models.BooleanField(default=False)),
                ('educationandcareer', models.BooleanField(default=False)),
                ('societyandpolitics', models.BooleanField(default=False)),
                ('fitnessandhealth', models.BooleanField(default=False)),
                ('marketingandsocialmedia', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
                ('photography', models.BooleanField(default=False)),
                ('Bank_FullName', models.CharField(default='', max_length=256)),
                ('Bank_acccountnumber', models.BigIntegerField()),
                ('Bank_IFSCcode', models.CharField(default='', max_length=11)),
                ('Paytm_FullName', models.CharField(default='', max_length=256)),
                ('Paytm_Number', models.IntegerField()),
                ('Gpay_FullName', models.CharField(default='', max_length=256)),
                ('Gpay_Number', models.IntegerField()),
                ('UPI_FullName', models.CharField(default='', max_length=256)),
                ('UPI_ID', models.CharField(default='', max_length=60)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup.accounts')),
                ('email', models.ForeignKey(help_text='Email: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
