# Generated by Django 3.1.3 on 2020-11-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Bank_FullName',
            new_name='bank_Full_Name',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Bank_IFSCcode',
            new_name='bank_IFSC_code',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Bank_acccountnumber',
            new_name='bank_acccount_number',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Gpay_FullName',
            new_name='gpay_Full_Name',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Gpay_Number',
            new_name='gpay_Number',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Paytm_FullName',
            new_name='paytm_Full_Name',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='Paytm_Number',
            new_name='paytm_Number',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='UPI_FullName',
            new_name='upi_Full_Name',
        ),
        migrations.RenameField(
            model_name='influencerlist',
            old_name='UPI_ID',
            new_name='upi_ID',
        ),
    ]
