# Generated by Django 3.1.3 on 2020-11-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0002_auto_20201122_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerlist',
            name='category',
            field=models.CharField(choices=[('Social Media Star', 'Social Media Star'), ('Mom/Dad Influencer', 'Mom/Dad Influencer'), ('Free Lancer', 'Free Lancer'), ('Campus Ambassador', 'Campus Ambassador'), ('Working Professional', 'Working Professional')], max_length=40),
        ),
        migrations.AlterField(
            model_name='influencerlist',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='influencerlist',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='influencerlist',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='influencerlist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='influencerlist',
            name='location',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='influencerlist',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
