# Generated by Django 3.1.2 on 2020-11-23 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0004_auto_20201122_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('location', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Social Media Star', 'Social Media Star'), ('Mom/Dad Influencer', 'Mom/Dad Influencer'), ('Free Lancer', 'Free Lancer'), ('Campus Ambassador', 'Campus Ambassador'), ('Working Professional', 'Working Professional')], max_length=40)),
                ('instagram_username', models.CharField(default='', max_length=256)),
                ('instagram_followers', models.IntegerField(default=50)),
                ('twitter_username', models.CharField(default='', max_length=256)),
                ('twitter_followers', models.IntegerField(default=50)),
                ('youtube_username', models.CharField(default='', max_length=256)),
                ('youtube_followers', models.IntegerField(default=50)),
                ('linkedin_username', models.CharField(default='', max_length=256)),
                ('linkedin_followers', models.IntegerField(default=50)),
                ('snapchat_username', models.CharField(default='', max_length=256)),
                ('snapchat_followers', models.IntegerField(default=50)),
                ('pinterest_username', models.CharField(default='', max_length=256)),
                ('pinterest_followers', models.IntegerField(default=50)),
                ('tumbler_username', models.CharField(default='', max_length=256)),
                ('tumbler_followers', models.IntegerField(default=50)),
                ('github_username', models.CharField(default='', max_length=256)),
                ('github_followers', models.IntegerField(default=50)),
                ('dribble_username', models.CharField(default='', max_length=256)),
                ('dribble_followers', models.IntegerField(default=50)),
                ('reddit_username', models.CharField(default='', max_length=256)),
                ('reddit_followers', models.IntegerField(default=50)),
                ('weddingmakeup', models.BooleanField(default=True)),
                ('clinicalmedicine', models.BooleanField(default=False)),
                ('facepaint', models.BooleanField(default=False)),
                ('filmsandmovie', models.BooleanField(default=False)),
                ('influencermakeup', models.BooleanField(default=False)),
                ('skincare', models.BooleanField(default=False)),
                ('bank_Full_Name', models.CharField(default='', max_length=256)),
                ('bank_acccount_number', models.BigIntegerField()),
                ('bank_IFSC_code', models.CharField(default='', max_length=11)),
                ('paytm_Full_Name', models.CharField(default='', max_length=256)),
                ('paytm_Number', models.IntegerField()),
                ('gpay_Full_Name', models.CharField(default='', max_length=256)),
                ('gpay_Number', models.IntegerField()),
                ('upi_Full_Name', models.CharField(default='', max_length=256)),
                ('upi_ID', models.CharField(default='', max_length=60)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup.accounts')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InfluencerList',
        ),
    ]
