# Generated by Django 3.1.2 on 2020-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20201123_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuplist',
            name='category',
            field=models.CharField(choices=[('Social Media Markup Artist', 'Social Media Markup Artist'), ('Freelancer', 'Freelancer'), ('Student', 'Student'), ('Working Professional', 'Working Professional')], max_length=40),
        ),
    ]
