# Generated by Django 3.1.2 on 2020-11-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20201123_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuplist',
            name='dribble_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='dribble_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='github_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='github_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='instagram_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='linkedin_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='linkedin_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='pinterest_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='pinterest_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='reddit_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='reddit_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='snapchat_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='snapchat_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='tumbler_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='tumbler_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='twitter_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='youtube_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='youtube_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
