# Generated by Django 3.1.2 on 2020-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20201123_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuplist',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
