# Generated by Django 3.1.2 on 2020-11-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20201123_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuplist',
            name='facebook_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
