# Generated by Django 3.1.2 on 2020-11-24 14:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20201124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuplist',
            name='ca_capacity',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='ca_college_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='ca_committee',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='ca_course',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='ca_worked_hobnob',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='ca_year_of_study',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Forth Year', 'Forth Year'), ('Fifth Year', 'Fifth Year')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='free_assign_done',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='free_date_assign',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='free_no_experience',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='influencer_choice',
            field=models.CharField(blank=True, choices=[('Do you have an active social circle of friends in your neighborhood?', 'Do you have an active social circle of friends in your neighborhood?'), ("Yes, I'm popular and I know it! :)", "Yes, I'm popular and I know it! :)"), ("No, I'm new & just getting to know people", "No, I'm new & just getting to know people"), ('Sort of, I have some friends, and keen to grow my circle of friends', 'Sort of, I have some friends, and keen to grow my circle of friends')], max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='mdi_old_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='mdi_young_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='sms_agency_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='sms_agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='sms_agent_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='sms_agent_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='wp_company_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='wp_designation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
