# Generated by Django 3.1.2 on 2020-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20201124_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuplist',
            name='gpay_Full_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='gpay_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='paytm_Full_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='paytm_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='upi_Full_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='makeuplist',
            name='upi_ID',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
