# Generated by Django 3.1.2 on 2020-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_auto_20201124_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuplist',
            name='influencer_choice',
            field=models.CharField(blank=True, choices=[('Do you have an active social circle of friends in your neighborhood?', 'Do you have an active social circle of friends in your neighborhood?'), ("Yes, I'm popular and I know it! :)", "Yes, I'm popular and I know it! :)"), ("No, I'm new & just getting to know people", "No, I'm new & just getting to know people"), ('Sort of, I have some friends, and keen to grow my circle of friends', 'Sort of, I have some friends, and keen to grow my circle of friends')], max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='mdi_old_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='makeuplist',
            name='mdi_young_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
